PREFIX piirrite: <http://piirrite.univ-lyon1.fr/ontology/core#>
PREFIX saref: <https://saref.etsi.org/core/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>
PREFIX pcv: <http://piirrite.univ-lyon1.fr/vocabulary#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX : <http://piirrite.univ-lyon1.fr/data#>

# CQ_1. What are the points of interest located within a 100-metre radius of a user?
SELECT ?poi ?wkt ?distance
WHERE {
  	# Arbitrarily initialize the user location
    BIND("POINT(4.87 45.78)"^^geo:wktLiteral AS ?userWKT)
    # Get all candidate PoIs
    ?poi a piirrite:PointOfInterest .
    ?poi geo:hasGeometry ?poiGeom .
    ?poiGeom geo:asWKT ?wkt .
    # Compute the distance between the user and each PoI
    BIND(geof:distance(?userWKT, ?wkt, uom:metre) AS ?distance)
    # Filter based on the distance
    FILTER(?distance <= 100)
}
ORDER BY ASC(?distance)

# CQ_2. Which navigable polylines pass by a given point of interest of the campus?
SELECT ?path ?wkt
WHERE {
    # Get all candidate Paths
    ?path a piirrite:NavigablePath .

    # Paths have to pass by the arbitrarily chosen PoI
    ?path piirrite:passesBy :ptoi_12165932287 .

    # Optionnaly retrieving the paths geometries
    OPTIONAL {
        ?path geo:hasGeometry ?geom .
        ?geom geo:asWKT ?wkt .
    }
}

# CQ_3. Which areas of interest are wheelchair-accessible?
SELECT DISTINCT ?aoi
WHERE {
    # Get all AoI with at least one specified property
    ?aoi a piirrite:AreaOfInterest ;
         saref:hasPropertyValue ?pv .
    
    # Filter by wheelchair-accessibility
    ?pv saref:isValueOfProperty pcv:P_Wheelchair ;
        saref:hasValue "yes" .
}

# CQ_4. Where is the nearest vending machine to a bicycle park with a capacity of at least 20?
SELECT ?vendingMachine ?vmGeom (MIN(?distance) AS ?minDistance)
WHERE {
    # Get candidate vending machines
    ?vendingMachine a piirrite:PointOfInterest ;
        geo:hasGeometry ?vmGeomNode .
    ?vmGeomNode geo:asWKT ?vmGeom .
    ?vendingMachine saref:hasPropertyValue ?pvVending .
    ?pvVending saref:isValueOfProperty pcv:P_Amenity ;
               saref:hasValue "vending_machine" .

    # Get all bycicle parks with a specified capacity
    ?bicycleParking a piirrite:PointOfInterest ;
        saref:hasFeatureKind pcv:K_BicycleParking ;
        geo:hasGeometry ?bpGeomNode ;
        saref:hasPropertyValue ?pvCapacity .
    ?bpGeomNode geo:asWKT ?bpGeom .
    ?pvCapacity saref:isValueOfProperty pcv:P_Capacity ;
                saref:hasValue ?capacityValue .

    # Filter by capacity
    FILTER(xsd:integer(?capacityValue) >= 20)

    # Compute each distance
    BIND(geof:distance(?vmGeom, ?bpGeom, <http://www.opengis.net/def/uom/OGC/1.0/metre>) AS ?distance)
}
GROUP BY ?vendingMachine ?vmGeom
ORDER BY ?minDistance
LIMIT 1 # Keep only the shortest distance

# CQ_5. Has it rained on the campus during the past two days?
ASK
WHERE {
  # Get all AoI
  ?aoi a piirrite:AreaOfInterest .

  # Filter based on whether they have a precipitation-related property value
  ?aoi saref:hasPropertyValue ?pv .
  ?pv  saref:isValueOfProperty pcv:P_precipitation ;
       saref:hasValue           ?precipitationValue .

  # Retrieve the temporal validity window of the precipitation-related property value;
  ?pv piirrite:hasTemporalValidity ?interval .
  ?interval time:hasBeginning ?beginInstant ;
            time:hasEnd       ?endInstant .

  ?beginInstant time:inXSDDateTimeStamp ?beginDate .
  ?endInstant   time:inXSDDateTimeStamp ?endDate .

  # Filter : stricly positive precipitation AND happened in the last two days
  # "Today" = June, 9th 2026
  FILTER (
    ?precipitationValue > 0 &&
    ?endDate   >= "2026-06-07T00:00:00"^^xsd:dateTime &&
    ?beginDate <= "2026-06-08T23:59:59"^^xsd:dateTime
  )
}

# CQ_6. Which navigable paths pass through the area with the highest pollen levels on May 1st, 2026?
SELECT ?path ?pathWKT ?aoi ?aoiWKT
WHERE {
  {
    # Subrequest to get the AoI with the highest pollen levels on May 1st, 2026
    SELECT ?aoi (MAX(xsd:decimal(?pollenValue)) AS ?maxPollen)
    WHERE {
      ?aoi a piirrite:AreaOfInterest ;
           saref:hasPropertyValue ?pv .

      ?pv saref:isValueOfProperty pcv:P_pollen_intensity ;
          saref:hasValue ?pollenValue ;
          piirrite:hasTemporalValidity ?interval .

      ?interval time:hasBeginning ?beginInstant ;
                time:hasEnd ?endInstant .

      ?beginInstant time:inXSDDate ?beginDate .
      ?endInstant   time:inXSDDate ?endDate .

      FILTER (
        ?beginDate = "2026-05-01"^^xsd:date ||
        ?endDate   = "2026-05-01"^^xsd:date
      )
    }
    GROUP BY ?aoi
    ORDER BY DESC(?maxPollen)
    LIMIT 1
  }

  ?aoi geo:hasGeometry ?aoiGeom .
  ?aoiGeom geo:asWKT ?aoiWKT .

  ?path a piirrite:NavigablePath ;
        geo:hasGeometry ?pathGeom .

  ?pathGeom geo:asWKT ?pathWKT .

  # Get all paths that intersect with the geometry of the previously retrieved AoI
  FILTER (geof:sfIntersects(?pathWKT, ?aoiWKT))
}
